# Generated by Django 4.1.5 on 2023-01-14 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_verification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.PositiveBigIntegerField(verbose_name='ID пользователя из телеграма')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Имя пользователя')),
                ('activating_bot', models.CharField(max_length=50, verbose_name='Активация бота')),
                ('goal', models.CharField(blank=True, max_length=50, verbose_name='есть цель')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('income', models.IntegerField(blank=True, null=True, verbose_name='Доход')),
                ('data', models.CharField(max_length=15, verbose_name='Дата покупки')),
            ],
            options={
                'verbose_name': 'Аутентификации пользователя',
                'verbose_name_plural': 'Аутентификации пользователя',
            },
        ),
        migrations.CreateModel(
            name='Purposes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.CharField(blank=True, max_length=50, verbose_name='купить машину')),
                ('apartment', models.CharField(blank=True, max_length=50, verbose_name='купить квартиру')),
                ('vacation', models.CharField(blank=True, max_length=50, verbose_name='съездить в отпуск')),
                ('another_target', models.CharField(blank=True, max_length=50, verbose_name='другие траты')),
                ('verification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db_analyst.user_verification')),
            ],
            options={
                'verbose_name': 'Цели',
                'verbose_name_plural': 'Цели',
            },
        ),
    ]
