# Generated by Django 4.1.5 on 2023-01-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_analyst', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_verification',
            name='user_id',
            field=models.PositiveBigIntegerField(null=True, verbose_name='ID пользователя из телеграма'),
        ),
    ]
